version: "3"
services:
  rust:
    image: rust
    container_name: rust
    environment:
      - SERVER_PORT=28015
      - SERVER_HOSTNAME=LemonAid
      - SERVER_SEED=32345
      - SERVER_SAVE_INTERVAL=300
      - SERVER_MAX_PLAYERS=75
      - SERVER_WORLD_SIZE=4092
    ports:
      - "28015:28015/udp"
      - "28016:28016"
    volumes: 
      - ./data:/data
    restart: unless-stopped